 # Generated by Django 4.2.6 on 2023-10-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10)),
                ('nation', models.CharField(max_length=100)),
                ('classs', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('address', models.CharField(max_length=300)),
                ('mssv', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('cccd', models.IntegerField()),
                ('nameFather', models.CharField(max_length=100)),
                ('nameMother', models.CharField(max_length=100)),
                ('phoneContact', models.IntegerField()),
            ],
        ),
    ]
