# Generated by Django 4.2.6 on 2023-10-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
