# Generated by Django 4.2.6 on 2023-10-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Management', '0003_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='cccd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phoneContact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
