# Generated by Django 4.2.7 on 2023-11-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Management', '0008_remove_student_namefather_remove_student_namemother_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='K56DVT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10)),
                ('nation', models.CharField(max_length=100)),
                ('classs', models.CharField(max_length=10)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=300)),
                ('mssv', models.CharField(max_length=30)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=50)),
                ('cccd', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
