# Generated by Django 4.2.7 on 2023-11-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Management', '0009_k56dvt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='k56dvt',
            name='age',
        ),
        migrations.RemoveField(
            model_name='k56dvt',
            name='cccd',
        ),
        migrations.RemoveField(
            model_name='k56dvt',
            name='nation',
        ),
    ]
