# Generated by Django 4.2.7 on 2023-11-13 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student_Management', '0010_remove_k56dvt_age_remove_k56dvt_cccd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
