# Generated by Django 4.2.2 on 2023-11-13 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student_Management', '0011_student_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Post_Image'),
        ),
        migrations.CreateModel(
            name='Model_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, null=True, upload_to='doc')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Doc_Image')),
                ('name', models.CharField(max_length=255)),
                ('name_author', models.CharField(max_length=255)),
                ('create_at', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
