# Generated by Django 4.2.2 on 2023-11-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Management', '0012_alter_model_post_image_model_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k56dvt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='K56DVT_Image'),
        ),
        migrations.AlterField(
            model_name='new_act',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='new_Image'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Student_Image'),
        ),
    ]
