# Generated by Django 4.2.2 on 2023-11-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Management', '0014_alter_k56dvt_image_alter_model_file_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k56dvt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='k56_image'),
        ),
        migrations.AlterField(
            model_name='model_file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='file_image'),
        ),
        migrations.AlterField(
            model_name='model_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image'),
        ),
        migrations.AlterField(
            model_name='new_act',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='new_image'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_image'),
        ),
    ]
