# Generated by Django 4.2.2 on 2023-12-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Management', '0017_new_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_job',
            name='description',
        ),
    ]
