# Generated by Django 4.2.2 on 2023-12-04 10:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Management', '0018_remove_new_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_job',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
