# Generated by Django 4.2.2 on 2023-12-05 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Management', '0019_new_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cccd',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
