# Generated by Django 4.2.2 on 2023-12-07 13:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Management', '0022_remove_student_address_remove_student_birthday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='description',
            new_name='act',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.AddField(
            model_name='student',
            name='study',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
